[package]
name = "pgp-encryption"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.4"
sequoia-openpgp = "1.16"
clap = { version = "4", features = ["derive"] }

[dev-dependencies]
tempfile = "3.8"
